from sqlalchemy import Column, Integer, String, ForeignKey, Boolean, DateTime, Enum, TIMESTAMP, Text
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from database import Base
from enum import Enum as PyEnum
from datetime import datetime
from pydantic import BaseModel, Field

class Gator(Base):
    __tablename__ = 'Gator'
    # Change # to number
    id = Column(Integer, primary_key=True, index=True)
    wb_id = Column(Integer)
    barcode = Column(String(15))
    title_no = Column(Integer) 
    title_desc = Column(String(100))
    mpm_number = Column(Integer)  # Changed # to "number"
    ep_title = Column(String(100))
    episode_number = Column(String(100)) # Changed # to "number"
    med_fmt = Column(String(100))
    element = Column(String(100))
    size = Column(String(100))
    standard = Column(String(100))
    localized = Column(String(100))
    language_1 = Column(String(100))
    language_2 = Column(String(100))
    langauge_3 = Column(String(100))
    langauge_4 = Column(String(100))
    content = Column(String(100))
    audio_mix = Column(String(100))
    audio_format =Column(String(100))
    audio_appl = Column(String(100))
    asset_desc = Column(String(100))
    track_config = Column(String(100))
    film_aspect = Column(String(100))
    audio_bit_rate = Column(String(100))
    video_aspect = Column(String(100))
    text = Column(String(100))
    music_effects = Column(String(10))
    version = Column(String(100))
    file_type = Column(String(10))
    container = Column(String(100))
    container_1 = Column(String(100))
    container_2 = Column(String(100))
    category = Column(String(100))
    title_option = Column(String(100))
    asset_type = Column(String(100))
    status = Column(String(20))
    active = Column(String(20))
    being_made_by = Column(String(100))
    current_facility = Column(String(100))
    home_facility = Column(String(100))
    library = Column(String(100))
    material = Column(String(100))
    process = Column(String(100))
    set_length = Column(String(100))
    no_of_units = Column(String(100))
    shelf = Column(String(100))
    reel_notes = Column(String(100))
    reel_tag = Column(String(100))
    frame_rate = Column(String(100))
    rating = Column(String(100))
    coloring = Column(String(100))
    stock_material = Column(String(100))
    create_date = Column(String(100))
    gator_mpm_number = Column(String(20)) # Changed # to "number"
    movement_reserved = Column(String(100))
    qc_status = Column(String(100))
    condition = Column(String(100))
    print_number = Column(String(100)) # Changed # to "number"
    inv_type = Column(String(100))
    asset_note = Column(Text)
    sync_system = Column(String(100))
    container_wb_id = Column(String(100))
    container_barcode = Column(String(100))
    reserved = Column(String(100))
    asset_set_id = Column(Integer)
    set_no = Column(Integer)
    set_total = Column(Integer)
    part_asset_no = Column(Integer)
    run_time = Column(String(100))
    owner = Column(String(100))
    alert_not_no_text = Column(String(100))
    title_in_package = Column(String(100))
    title_type = Column(String(100))
    story_time = Column(String(100))
    track_assign = Column(String(100))
    title_version = Column(String(100))
    title_no_episodic_mpm = Column(Integer) ## NEED CHECK
    localization = Column(String(100))
    enviroment = Column(String(100))
    vault = Column(String(100))
    user_added = Column(String(100))
    user_changed = Column(String(100))
    original_system = Column(String(100))
    